// @ts-check
// Root lint config for the non-client packages (ingest/schema/secrets/shared).
// The client has its own stricter, type-checked config at
// packages/client/eslint.config.mjs (generated by our shadcn fork); flat config
// does not cascade, so `eslint .` here intentionally ignores it and the root
// `lint` script runs the client's config separately.
import js from '@eslint/js'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/build/**',
      '**/node_modules/**',
      '**/coverage/**',
      'poc/**',
      'apps/client/**',
      '**/*.config.{js,ts,mjs}',
      '**/scripts/**'
    ]
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      '@typescript-eslint/consistent-type-imports': 'error'
    }
  }
)
